In [182]:
import pandas as pd
import numpy as np

In [184]:
df = pd.read_csv('../data/processed/combined_by_year/combined_all_years.csv')

In [186]:
df.head()

,County,State,mean_life_expectancy,State_FIPS,County_FIPS,disability_rate,white_population,total_population,age_60_and_over,poverty_rate,...,unemployment_rate,median_household_income,asian_population,per_capita_income,total_population_race,high_school_only_percentage,median_home_value,black_population,age_18_and_under_percentage,Year
0,Abbeville County,South Carolina,76.554614,45,1,19.7,17759.0,25387.0,14.7,20.8,...,13.7,35067.0,17759.0,17876.0,25387.0,34.8,90300.0,7144.0,10.2,2012
1,Acadia Parish,Louisiana,74.133702,22,1,17.9,48543.0,61611.0,10.9,19.1,...,8.6,38686.0,48543.0,19369.0,61611.0,42.2,88900.0,11184.0,9.9,2012
2,Accomack County,Virginia,75.798941,51,1,11.8,22586.0,33454.0,17.5,20.2,...,7.0,40780.0,22586.0,22909.0,33454.0,39.3,153800.0,9620.0,8.0,2012
3,Ada County,Idaho,80.699209,16,1,9.6,363070.0,394961.0,9.3,12.2,...,8.5,55499.0,363070.0,27522.0,394961.0,20.8,193300.0,4057.0,9.2,2012
4,Adair County,Iowa,78.760544,19,1,13.7,7457.0,7628.0,18.6,9.9,...,4.0,47872.0,7457.0,25147.0,7628.0,45.5,96700.0,11.0,7.1,2012

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24888 entries, 0 to 24887
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   County                          24888 non-null  object
 1   State                           24888 non-null  object
 2   mean_life_expectancy            24888 non-null  float64
 3   State_FIPS                      24888 non-null  int64
 4   County_FIPS                     24888 non-null  int64
 5   disability_rate                 24872 non-null  float64
 6   white_population                24872 non-null  float64
 7   total_population                24872 non-null  float64
 8   age_60_and_over                 24872 non-null  float64
 9   poverty_rate                    24871 non-null  float64
 10  housing_cost_burden             24871 non-null  float64
 11  bachelors_and_above_percentage  24872 non-null  float64
 12  median_gross_rent               24871 non-null  float64
 13  age_15_to_44_percentage         24872 non-null  float64
 14  gini_index                      24871 non-null  float64
 15  native_american_population      24872 non-null  float64
 16  less_than_9th_grade_percentage  24872 non-null  float64
 17  health_insurance_rate           24872 non-null  float64
 18  unemployment_rate               24871 non-null  float64
 19  median_household_income         24871 non-null  float64
 20  asian_population                24872 non-null  float64
 21  per_capita_income               24871 non-null  float64
 22  total_population_race           24872 non-null  float64
 23  high_school_only_percentage     24872 non-null  float64
 24  median_home_value               24872 non-null  float64
 25  black_population                24872 non-null  float64
 26  age_18_and_under_percentage     24872 non-null  float64
 27  Year                            24888 non-null  int64
dtypes: float64(23), int64(3), object(2)
memory usage: 5.3+ MB

In [190]:
df.isna().sum()

County                             0
State                              0
mean_life_expectancy               0
State_FIPS                         0
County_FIPS                        0
disability_rate                   16
white_population                  16
total_population                  16
age_60_and_over                   16
poverty_rate                      17
housing_cost_burden               17
bachelors_and_above_percentage    16
median_gross_rent                 17
age_15_to_44_percentage           16
gini_index                        17
native_american_population        16
less_than_9th_grade_percentage    16
health_insurance_rate             16
unemployment_rate                 17
median_household_income           17
asian_population                  16
per_capita_income                 17
total_population_race             16
high_school_only_percentage       16
median_home_value                 16
black_population                  16
age_18_and_under_percentage       16
Year                               0
dtype: int64

In [192]:
# Looking up the rows that have empty values

df[df.isna().any(axis=1)]

,County,State,mean_life_expectancy,State_FIPS,County_FIPS,disability_rate,white_population,total_population,age_60_and_over,poverty_rate,...,unemployment_rate,median_household_income,asian_population,per_capita_income,total_population_race,high_school_only_percentage,median_home_value,black_population,age_18_and_under_percentage,Year
6385,Bedford City,Virginia,79.092321,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014
9496,Bedford City,Virginia,78.803178,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
11911,Shannon County,South Dakota,65.981286,46,113,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
12013,Storey County,Nevada,81.880836,32,29,23.6,3703.0,3929.0,24.7,7.5,...,10.3,64832.0,3703.0,35115.0,3929.0,29.5,177000.0,17.0,1.8,2015
12208,Wade Hampton Census Area,Alaska,68.803238,2,270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015
12607,Bedford City,Virginia,78.717499,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
15022,Shannon County,South Dakota,65.358475,46,113,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
15319,Wade Hampton Census Area,Alaska,68.237443,2,270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016
15718,Bedford City,Virginia,78.793568,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
18133,Shannon County,South Dakota,65.340021,46,113,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
18430,Wade Hampton Census Area,Alaska,67.985913,2,270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
18829,Bedford City,Virginia,78.839479,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
21067,Rio Arriba County,New Mexico,73.986119,35,39,16.1,21382.0,39307.0,25.6,NaN,...,NaN,NaN,21382.0,NaN,39307.0,31.3,164800.0,237.0,23.7,2018
21244,Shannon County,South Dakota,65.176273,46,113,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
21541,Wade Hampton Census Area,Alaska,68.291970,2,270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
21940,Bedford City,Virginia,79.034724,51,515,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
24355,Shannon County,South Dakota,65.423111,46,113,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
24652,Wade Hampton Census Area,Alaska,68.561804,2,270,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019

In [194]:
# Deleting all the rows with empty values and creating a new dataframe 

df_cleaned = df.dropna()

In [196]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24870 entries, 0 to 24887
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   County                          24870 non-null  object
 1   State                           24870 non-null  object
 2   mean_life_expectancy            24870 non-null  float64
 3   State_FIPS                      24870 non-null  int64
 4   County_FIPS                     24870 non-null  int64
 5   disability_rate                 24870 non-null  float64
 6   white_population                24870 non-null  float64
 7   total_population                24870 non-null  float64
 8   age_60_and_over                 24870 non-null  float64
 9   poverty_rate                    24870 non-null  float64
 10  housing_cost_burden             24870 non-null  float64
 11  bachelors_and_above_percentage  24870 non-null  float64
 12  median_gross_rent               24870 non-null  float64
 13  age_15_to_44_percentage         24870 non-null  float64
 14  gini_index                      24870 non-null  float64
 15  native_american_population      24870 non-null  float64
 16  less_than_9th_grade_percentage  24870 non-null  float64
 17  health_insurance_rate           24870 non-null  float64
 18  unemployment_rate               24870 non-null  float64
 19  median_household_income         24870 non-null  float64
 20  asian_population                24870 non-null  float64
 21  per_capita_income               24870 non-null  float64
 22  total_population_race           24870 non-null  float64
 23  high_school_only_percentage     24870 non-null  float64
 24  median_home_value               24870 non-null  float64
 25  black_population                24870 non-null  float64
 26  age_18_and_under_percentage     24870 non-null  float64
 27  Year                            24870 non-null  int64
dtypes: float64(23), int64(3), object(2)
memory usage: 5.5+ MB

In [198]:
df_cleaned.isna().sum()

County                            0
State                             0
mean_life_expectancy              0
State_FIPS                        0
County_FIPS                       0
disability_rate                   0
white_population                  0
total_population                  0
age_60_and_over                   0
poverty_rate                      0
housing_cost_burden               0
bachelors_and_above_percentage    0
median_gross_rent                 0
age_15_to_44_percentage           0
gini_index                        0
native_american_population        0
less_than_9th_grade_percentage    0
health_insurance_rate             0
unemployment_rate                 0
median_household_income           0
asian_population                  0
per_capita_income                 0
total_population_race             0
high_school_only_percentage       0
median_home_value                 0
black_population                  0
age_18_and_under_percentage       0
Year                              0
dtype: int64

In [200]:
df_cleaned.head()

,County,State,mean_life_expectancy,State_FIPS,County_FIPS,disability_rate,white_population,total_population,age_60_and_over,poverty_rate,...,unemployment_rate,median_household_income,asian_population,per_capita_income,total_population_race,high_school_only_percentage,median_home_value,black_population,age_18_and_under_percentage,Year
0,Abbeville County,South Carolina,76.554614,45,1,19.7,17759.0,25387.0,14.7,20.8,...,13.7,35067.0,17759.0,17876.0,25387.0,34.8,90300.0,7144.0,10.2,2012
1,Acadia Parish,Louisiana,74.133702,22,1,17.9,48543.0,61611.0,10.9,19.1,...,8.6,38686.0,48543.0,19369.0,61611.0,42.2,88900.0,11184.0,9.9,2012
2,Accomack County,Virginia,75.798941,51,1,11.8,22586.0,33454.0,17.5,20.2,...,7.0,40780.0,22586.0,22909.0,33454.0,39.3,153800.0,9620.0,8.0,2012
3,Ada County,Idaho,80.699209,16,1,9.6,363070.0,394961.0,9.3,12.2,...,8.5,55499.0,363070.0,27522.0,394961.0,20.8,193300.0,4057.0,9.2,2012
4,Adair County,Iowa,78.760544,19,1,13.7,7457.0,7628.0,18.6,9.9,...,4.0,47872.0,7457.0,25147.0,7628.0,45.5,96700.0,11.0,7.1,2012

In [202]:
df[(df == -666666666).any(axis=1)].count()

County                            12
State                             12
mean_life_expectancy              12
State_FIPS                        12
County_FIPS                       12
disability_rate                   12
white_population                  12
total_population                  12
age_60_and_over                   12
poverty_rate                      12
housing_cost_burden               12
bachelors_and_above_percentage    12
median_gross_rent                 12
age_15_to_44_percentage           12
gini_index                        12
native_american_population        12
less_than_9th_grade_percentage    12
health_insurance_rate             12
unemployment_rate                 12
median_household_income           12
asian_population                  12
per_capita_income                 12
total_population_race             12
high_school_only_percentage       12
median_home_value                 12
black_population                  12
age_18_and_under_percentage       12
Year                              12
dtype: int64

In [204]:
# Identifying the rows with -666666666

rows = df[(df == -666666666).any(axis=1)]
rows

,County,State,mean_life_expectancy,State_FIPS,County_FIPS,disability_rate,white_population,total_population,age_60_and_over,poverty_rate,...,unemployment_rate,median_household_income,asian_population,per_capita_income,total_population_race,high_school_only_percentage,median_home_value,black_population,age_18_and_under_percentage,Year
1449,Kalawao County,Hawaii,81.397789,15,5,6.6,38.0,66.0,26.5,10.9,...,0.0,66250.0,38.0,50618.0,66.0,12.1,-666666666.0,0.0,2.9,2012
4560,Kalawao County,Hawaii,81.530712,15,5,10.0,33.0,71.0,8.8,14.7,...,0.0,59375.0,33.0,45515.0,71.0,9.7,-666666666.0,0.0,8.8,2013
7671,Kalawao County,Hawaii,81.594061,15,5,12.3,32.0,73.0,9.1,17.6,...,0.0,61250.0,32.0,43771.0,73.0,13.3,-666666666.0,0.0,9.1,2014
10782,Kalawao County,Hawaii,81.552522,15,5,12.0,32.0,85.0,7.1,15.2,...,0.0,66250.0,32.0,46769.0,85.0,29.5,-666666666.0,0.0,9.5,2015
13080,Cottle County,Texas,75.717451,48,101,20.1,1197.0,1560.0,25.8,25.0,...,11.6,33750.0,1197.0,20397.0,1560.0,30.3,42600.0,235.0,11.3,2016
13893,Kalawao County,Hawaii,81.602279,15,5,19.5,29.0,91.0,2.3,12.9,...,0.0,65625.0,29.0,45812.0,91.0,36.9,-666666666.0,0.0,6.8,2016
16253,Daggett County,Utah,79.325538,49,9,9.8,677.0,702.0,22.2,4.0,...,1.0,85000.0,677.0,28533.0,702.0,43.3,202900.0,1.0,21.5,2017
17004,Kalawao County,Hawaii,81.654384,15,5,23.4,18.0,86.0,31.4,12.7,...,0.0,61750.0,18.0,46024.0,86.0,25.3,-666666666.0,0.0,2.3,2017
19551,Eureka County,Nevada,77.801223,32,11,18.0,1725.0,1830.0,26.2,7.7,...,0.0,77625.0,1725.0,34590.0,1830.0,39.0,84400.0,1.0,23.8,2018
20115,Kalawao County,Hawaii,81.884479,15,5,24.3,16.0,75.0,28.0,10.6,...,0.0,61875.0,16.0,47709.0,75.0,27.5,-666666666.0,2.0,5.3,2018
22662,Eureka County,Nevada,77.755777,32,11,17.2,1744.0,1859.0,28.2,8.0,...,0.0,67105.0,1744.0,34249.0,1859.0,47.4,120100.0,1.0,23.0,2019
23226,Kalawao County,Hawaii,81.987448,15,5,24.6,16.0,66.0,27.3,10.0,...,0.0,69375.0,16.0,49118.0,66.0,27.4,-666666666.0,2.0,1.5,2019

In [206]:
# Dropping the rows with -666666666 and creating a new dataframe

df_cleaned_final = df_cleaned[(df_cleaned != -666666666).all(axis=1)]

In [208]:
df_cleaned_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24858 entries, 0 to 24887
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   County                          24858 non-null  object
 1   State                           24858 non-null  object
 2   mean_life_expectancy            24858 non-null  float64
 3   State_FIPS                      24858 non-null  int64
 4   County_FIPS                     24858 non-null  int64
 5   disability_rate                 24858 non-null  float64
 6   white_population                24858 non-null  float64
 7   total_population                24858 non-null  float64
 8   age_60_and_over                 24858 non-null  float64
 9   poverty_rate                    24858 non-null  float64
 10  housing_cost_burden             24858 non-null  float64
 11  bachelors_and_above_percentage  24858 non-null  float64
 12  median_gross_rent               24858 non-null  float64
 13  age_15_to_44_percentage         24858 non-null  float64
 14  gini_index                      24858 non-null  float64
 15  native_american_population      24858 non-null  float64
 16  less_than_9th_grade_percentage  24858 non-null  float64
 17  health_insurance_rate           24858 non-null  float64
 18  unemployment_rate               24858 non-null  float64
 19  median_household_income         24858 non-null  float64
 20  asian_population                24858 non-null  float64
 21  per_capita_income               24858 non-null  float64
 22  total_population_race           24858 non-null  float64
 23  high_school_only_percentage     24858 non-null  float64
 24  median_home_value               24858 non-null  float64
 25  black_population                24858 non-null  float64
 26  age_18_and_under_percentage     24858 non-null  float64
 27  Year                            24858 non-null  int64
dtypes: float64(23), int64(3), object(2)
memory usage: 5.5+ MB

In [210]:
df_cleaned_final[(df_cleaned_final == -666666666).any(axis=1)].count()

County                            0
State                             0
mean_life_expectancy              0
State_FIPS                        0
County_FIPS                       0
disability_rate                   0
white_population                  0
total_population                  0
age_60_and_over                   0
poverty_rate                      0
housing_cost_burden               0
bachelors_and_above_percentage    0
median_gross_rent                 0
age_15_to_44_percentage           0
gini_index                        0
native_american_population        0
less_than_9th_grade_percentage    0
health_insurance_rate             0
unemployment_rate                 0
median_household_income           0
asian_population                  0
per_capita_income                 0
total_population_race             0
high_school_only_percentage       0
median_home_value                 0
black_population                  0
age_18_and_under_percentage       0
Year                              0
dtype: int64

In [212]:
output_dir = '../data/cleaned/combined_all_years_cleaned.csv'

In [214]:
df_cleaned_final.to_csv(output_dir, index=False)